opti:
  - O0
  - O1
  - O2
  - O3
  - Os
  - Ofast

arch:
  - x86_32
  - x86_64
  - arm_32
  - arm_64
  - mips_32
  - mips_64
  - mipseb_32
  - mipseb_64

compiler:
  - gcc-4.9.4
  - gcc-5.5.0
  - gcc-6.5.0
  - gcc-7.3.0
  - gcc-8.2.0
  - gcc-9.4.0
  - gcc-10.3.0
  - gcc-11.2.0
  - clang-4.0
  - clang-5.0
  - clang-6.0
  - clang-7.0
  - clang-8.0
  - clang-9.0
  - clang-10.0
  - clang-11.0
  - clang-12.0
  - clang-13.0

